var name = 'VirtualBookshelf';
var exports = window[name] || (window[name] = {});
exports['Bookshelf'] = Bookshelf;
exports['Carousel'] = Carousel;
exports['Train'] = Train;
exports['ArrayStream'] = ArrayStream;
exports['JSONStream'] = JSONStream;
exports['FadeTransition'] = FadeTransition;
exports['SimpleItem'] = SimpleItem;
exports['SubstituteImage'] = SubstituteImage;